"""reparto clientes

Revision ID: 293a48ed1218
Revises: 960ba6276643
Create Date: 2026-01-18 12:33:38.018390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293a48ed1218'
down_revision = '960ba6276643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparto_clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.alter_column('cliente_codigo',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_hub_cliente_codigo'), type_='unique')
        batch_op.drop_column('activo')
        batch_op.drop_column('ruta_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparto_clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_code', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_hub_cliente_codigo'), ['hub_id', 'cliente_codigo'])
        batch_op.alter_column('cliente_codigo',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.drop_column('active')
        batch_op.drop_column('estado')
        batch_op.drop_column('route_id')

    # ### end Alembic commands ###
