"""add comment to kilos/litros

Revision ID: 485c2fd57d96
Revises: 2e395140108f
Create Date: 2026-01-01 20:40:23.980280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485c2fd57d96'
down_revision = '2e395140108f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kilos_litros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('ruta_numero', sa.Integer(), nullable=False),
    sa.Column('clientes', sa.Integer(), nullable=False),
    sa.Column('kilos', sa.Float(), nullable=False),
    sa.Column('litros', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hub_id', 'year', 'month', 'ruta_numero', 'active', name='uq_hub_year_month_ruta_kilos_litros')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kilos_litros')
    # ### end Alembic commands ###
