"""add estado to reparto_clientes

Revision ID: 6a3a5a7ec35c
Revises: <PON_AQUI_EL_ID_QUE_TE_CREO_FLASK>
Create Date: 2026-01-18 14:18:18.985620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3a5a7ec35c'
down_revision = '<PON_AQUI_EL_ID_QUE_TE_CREO_FLASK>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparto_clientes', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=220),
               existing_nullable=False)
        batch_op.alter_column('direccion',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.drop_column('active')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparto_clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('direccion',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=220),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
