"""add comment to liquidacion_entries

Revision ID: 730ffd5b19a7
Revises: bce7ddb89227
Create Date: 2025-12-27 21:29:06.764814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730ffd5b19a7'
down_revision = 'bce7ddb89227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion_entries', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
