"""add comment to kilos/litros

Revision ID: 7381c6138023
Revises: 485c2fd57d96
Create Date: 2026-01-01 21:38:48.593656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7381c6138023'
down_revision = '485c2fd57d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_kilos_litros')
    with op.batch_alter_table('kilos_litros', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_hub_year_month_ruta_kilos_litros'), type_='unique')
        batch_op.create_unique_constraint('uq_hub_day_ruta_kilos', ['hub_id', 'day', 'ruta_numero', 'active'])
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kilos_litros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('uq_hub_day_ruta_kilos', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_hub_year_month_ruta_kilos_litros'), ['hub_id', 'year', 'month', 'ruta_numero', 'active'])

    op.create_table('_alembic_tmp_kilos_litros',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hub_id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('ruta_numero', sa.INTEGER(), nullable=False),
    sa.Column('clientes', sa.INTEGER(), nullable=False),
    sa.Column('kilos', sa.FLOAT(), nullable=False),
    sa.Column('litros', sa.FLOAT(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('day', sa.VARCHAR(length=10), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hub_id', 'day', 'ruta_numero', 'active', name=op.f('uq_hub_day_ruta_kilos'))
    )
    # ### end Alembic commands ###
