"""reparto clientes y heineken pedidos

Revision ID: 960ba6276643
Revises: 6cc76f3fd3b9
Create Date: 2026-01-18 11:54:20.843273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960ba6276643'
down_revision = '6cc76f3fd3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heineken_pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.Integer(), nullable=False),
    sa.Column('pedido_codigo', sa.String(length=60), nullable=False),
    sa.Column('cliente_codigo', sa.String(length=60), nullable=False),
    sa.Column('ruta_code', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('reprogramado_a', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heineken_pedidos', schema=None) as batch_op:
        batch_op.create_index('ix_pedido_hub_fecha_ruta_cliente', ['hub_id', 'fecha', 'ruta_code', 'cliente_codigo'], unique=False)

    op.create_table('reparto_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.Integer(), nullable=False),
    sa.Column('cliente_codigo', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=False),
    sa.Column('ruta_code', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hub_id', 'cliente_codigo', name='uq_hub_cliente_codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reparto_clientes')
    with op.batch_alter_table('heineken_pedidos', schema=None) as batch_op:
        batch_op.drop_index('ix_pedido_hub_fecha_ruta_cliente')

    op.drop_table('heineken_pedidos')
    # ### end Alembic commands ###
