"""flota incidencias historico

Revision ID: f3b4414559c3
Revises: f3c44a8bfb2b
Create Date: 2026-01-04 06:42:47.592031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b4414559c3'
down_revision = 'f3c44a8bfb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flota_incidencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flota_incidencias_vehiculo_fecha'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flota_incidencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flota_incidencias_vehiculo_fecha'), ['vehiculo_id', 'fecha'], unique=False)

    # ### end Alembic commands ###
